/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_mobile_analytics_app_id": "a3f110929cf84529ab0d4f92f166436c",
    "aws_mobile_analytics_app_region": "us-east-1",
    "Analytics": {
        "AWSPinpoint": {
            "appId": "a3f110929cf84529ab0d4f92f166436c",
            "region": "us-east-1"
        }
    },
    "Notifications": {
        "Push": {
            "AWSPinpoint": {
                "appId": "a3f110929cf84529ab0d4f92f166436c",
                "region": "us-east-1"
            }
        }
    },
    "aws_appsync_graphqlEndpoint": "https://we23ok3j5batbj42c6kztqzeqm.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-uwvmbjxisnbdhktxozzcyvqgva",
    "aws_cognito_identity_pool_id": "us-east-1:715ff03e-dbd0-4b30-bd0e-579aa9223e6a",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_iy52GqjhI",
    "aws_user_pools_web_client_id": "7fu4aqik355n8lv9bf9ros56pn",
    "oauth": {
        "domain": "sportzonb4154282-b4154282-dev.auth.us-east-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "sportzon://",
        "redirectSignOut": "sportzon://",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS",
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [
        "FACEBOOK",
        "GOOGLE",
        "APPLE"
    ],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "sportzon299a2ebea1ff43de9d0d5adbd16cb846134446-dev",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
