name: Deploy to EC2 with PM2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Deploy to EC2
        run: |
          # Add your deployment script here
          # e.g., scp and SSH to the EC2 instance to copy and start your Node.js application
          ssh -i {{ secrets.SSH_PRIVATE_KEY }} ec2-user@ec2-18-235-51-187.compute-1.amazonaws.com "cd /home/ec2-user/sportzon-api && git pull && npm install && pm2 restart app"
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Transfer files to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }} # EC2 instance public IP or DNS
          username: ${{ secrets.EC2_USER }} # SSH username
          key: ${{ secrets.SSH_PRIVATE_KEY }} # SSH private key
          source: "." # Source directory
          target: "/home/ec2-user/app" # Target directory on EC2

      - name: SSH into EC2 and deploy with PM2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }} # EC2 instance public IP or DNS
          username: ${{ secrets.EC2_USER }} # SSH username
          key: ${{ secrets.SSH_PRIVATE_KEY }} # SSH private key
          source: "." # Source directory
          target: "/home/ec2-user/app" # Target directory on EC2
          script: |
            whoami
