name: Deploy to EC2 with PM2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Transfer files to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }} # EC2 instance public IP or DNS
          username: ${{ secrets.EC2_USER }} # SSH username
          key: ${{ secrets.SSH_PRIVATE_KEY }} # SSH private key
          source: "." # Source directory
          target: "/home/ec2-user/app" # Target directory on EC2

      - name: SSH into EC2 and deploy with PM2
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > sportzon.pem
          chmod 600 sportzon.pem
          ssh -i "sportzon.pem" ec2-user@ec2-54-90-89-188.compute-1.amazonaws.com 'cd /home/ec2-user/app && pm2 start npm --name "sportzon" -- start'
