name: Deploy to EC2 with PM2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Deploy to EC2
        env:
          HOST: ${{ secrets.EC2_HOST }}
          USERNAME: ${{ secrets.EC2_USERNAME }}
          PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }}
        run: |
          echo ${{ secrets.SSH_PRIVATE_KEY }} > private_key.pem
          chmod 600 private_key.pem
          scp -i private_key.pem -r ./dist $USERNAME@$HOST:/path/to/remote/directory
          ssh -i private_key.pem $USERNAME@$HOST 'cd /path/to/remote/directory && pm2 restart sportzon'


      - name: Transfer files to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }} # EC2 instance public IP or DNS
          username: ${{ secrets.EC2_USER }} # SSH username
          key: ${{ secrets.SSH_PRIVATE_KEY }} # SSH private key
          source: "." # Source directory
          target: "/home/ec2-user/app" # Target directory on EC2

      - name: SSH into EC2 and deploy with PM2
        run: |
          ssh -i ${{ secrets.SSH_PRIVATE_KEY }} ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} 'cd /home/ec2-user/app && pm2 start npm --name "sportzon" -- start'
